### ISSUE TITLE
crun: could not get wasmedge process module context

### ISSUE THREAD

**Issue by hdp7891000** [second-state/wasmedge-containers-examples#18]
At first, I failed to compile crun:
    https://github.com/containers/crun/issues/934

I modified the code referring to this：
    https://github.com/containers/crun/pull/933

When I run simple_wasi_application.sh I get the following error:
```
    crun: could not get wasmedge process module context
    pod default/wasi-demo terminated (Error)
    Wait 60s
    NAMESPACE     NAME                       READY   STATUS             RESTARTS        AGE   IP          NODE        NOMINATED NODE   READINESS GATES
    default       wasi-demo                  0/1     Error              0               68s   127.0.0.1   127.0.0.1   <none>           <none>
    kube-system   coredns-755cd654d4-wxq5b   0/1     CrashLoopBackOff   12 (4m4s ago)   40m   10.88.0.2   127.0.0.1   <none>           <none>
```

**Comment by hydai** [comment]
Thanks for reporting. I already commented on the original thread. 
https://github.com/containers/crun/pull/933#issuecomment-1164317994

I will follow up and update this issue on the upstream.

**Comment by flouthoc** [comment]
@hdp7891000 @hydai  PR for dropping `WasmedgeProcess` here https://github.com/containers/crun/pull/962 will rebase this for `0.10.0` if that goes in before this :)

**Comment by hydai** [comment]
Thanks @flouthoc 
I think this issue is resolved. The `process` module will be back once it doesn't break any production `crun` environment.
