### ISSUE TITLE
containerd example can't work with crun 1.8.5

### ISSUE THREAD

**Issue by yizhimei502** [second-state/wasmedge-containers-examples#31]
I tried [containerd](https://github.com/second-state/wasmedge-containers-examples/tree/main/containerd), I follow your steps, but cant’ use ctr run the container. When i "ctr run" it show "ctr: failed to create shim: OCI runtime create failed: io priority not supported: unknown". How to fix the err？

**Comment by hydai** [comment]
Hi @woylhe 
Could you please provide the environment and software versions you used?

**Comment by yizhimei502** [comment]
ok. I used ubuntu20.04 and kernel is 5.15.0-71-generir

**Comment by hydai** [comment]
Could you also provide the `wasmedge` and `crun` versions? Since the installer can try to install different versions, it would be clear if you could give me more information.

**Comment by yizhimei502** [comment]
I Follow the readme to install, and the version is as follow: 
wasmedge 0.12.1
crun 1.8.5
ctr 1.5.7

**Comment by hydai** [comment]
`crun 1.8.5` may have some issues, and I've yet to figure it out. Could you try running the `install.sh` with `--crun=1.8.4`? I think it should work.

**Comment by yizhimei502** [comment]
Yes, it works, I use 1.8.4 and run container succ, thanks!

**Comment by hydai** [comment]
After verifying the crun 1.15, no error occurred again. Closing this.
