### ISSUE TITLE
how arm64 to work with crun. could you give new configfile of containerd

### ISSUE THREAD

**Issue by wangqianyv123** [second-state/wasmedge-containers-examples#36]
1.5.6 is amd64, when i changed arm64 version, it doesn't work correctly.

**Comment by hydai** [comment]
Do you build arm64 version with `--with-wasmedge` in the crun configuration?

**Comment by wangqianyv123** [comment]
thank you for your reply. it's okey now. i modify config of containerd personally, but don't use diff to patch.
